spring:
  datasource:
    url: jdbc:h2:mem:db_raffle
    username: raffle_adm
    password:
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false